// src/templates/files/react/resources/js/pages/errors/404.tsx
import { Head, Link } from '@inertiajs/react'

export default function NotFound() {
  return (
    <div className="error-page">
      <Head title="Not found" />
      <p className="status">404</p>
      <h1>Nothing here</h1>
      <p className="muted">That address does not match any route.</p>
      <Link className="button" href="/">
        Go home
      </Link>
    </div>
  )
}

// src/templates/files/svelte/resources/js/pages/errors/404.svelte
<script lang="ts">
  import { Link } from '@inertiajs/svelte'
</script>

<svelte:head>
  <title>Not found</title>
</svelte:head>

<div class="error-page">
  <p class="status">404</p>
  <h1>Nothing here</h1>
  <p class="muted">That address does not match any route.</p>
  <Link class="button" href="/">Go home</Link>
</div>
